name: mlops-ci

on:
  push:
    branches: 
      - main
      - feat/init-mlops-huggingface

jobs:

  train-model:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL
        run: python download_data.py

      - name: Run Data Quality
        run: python check_data.py

      - name: Train model
        run: python model_training.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            knn_sport_model.pkl
            sport_scaler.pkl
            sport_names.pkl

      - name: Push models to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "mixolydien@github.com"
          git config --global user.name "mixolydien"

          git clone https://$HF_TOKEN@huggingface.co/spaces/Mixolydien/sport-suggestion-api hf-space

          cp knn_sport_model.pkl hf-space/
          cp sport_scaler.pkl hf-space/
          cp sport_names.pkl hf-space/

          cd hf-space
          git add .
          git commit -m "Update model from CI pipeline"
          git push
